package com.automationteststore.enums;

public enum ConfigProperties {

    URL,
    OVERRIDEREPORTS,
    PASSEDSTEPSSCREENSHOTS,
    FAILEDSTEPSSCREENSHOTS,
    RETRYFAILEDTESTS,
    RUNMODE,
    SENDRESULTTOELK,
    SELENIUMGRIDURL,
    ELASTICURL,
    BROWSER

}
